---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rustfs-instance.name" . }}
  labels:
    {{- include "rustfs-instance.labels" . | nindent 4 }}
data:
  ACCESS_KEY: {{ .Values.username | toString | b64enc }}
  SECRET_KEY: {{ .Values.password | toString | b64enc }}
