# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  GREETING: Hello, world!

tasks:
  pre-commit-all:
    desc: Run pre-commit --all
    silent: true
    cmd: pre-commit run --all
  sync-crds:
    desc: Sync CRD from the operator to the chart
    silent: true
    vars:
      WORKDIR:
        sh: mktemp -d
    cmds:
      - cd operator && cargo run -- --print-crd  > {{.WORKDIR}}/crds.yaml
      - cd {{.WORKDIR}} && yq -s '.metadata.name + ".yaml"' crds.yaml && rm crds.yaml
      - rm -rf ./charts/rustfs-manager-operator/crd/*
      - cp {{.WORKDIR}}/* ./charts/rustfs-manager-operator/crd/
      - rm -rf {{.WORKDIR}}
  bump-version:
    desc: Set a new version everywhere
    silent: false
    cmds:
      - yq -i '.package.version = "{{.CLI_ARGS}}"' ./operator/Cargo.toml
      - cd ./operator && cargo generate-lockfile
      - poetry --project ./documentation/ version "{{.CLI_ARGS}}"
      - yq -i '.version = "{{.CLI_ARGS}}"' ./charts/rustfs-instance/Chart.yaml
      - yq -i '.appVersion = "{{.CLI_ARGS}}"' ./charts/rustfs-instance/Chart.yaml
      - yq -i '.version = "{{.CLI_ARGS}}"' ./charts/rustfs-manager-operator/Chart.yaml
      - yq -i '.appVersion = "{{.CLI_ARGS}}"' ./charts/rustfs-manager-operator/Chart.yaml
      - yq -i '.version = "{{.CLI_ARGS}}"' ./charts/rustfs-manager-operator-docs/Chart.yaml
      - yq -i '.appVersion = "{{.CLI_ARGS}}"' ./charts/rustfs-manager-operator-docs/Chart.yaml
  unit-tests:
    desc: Execute unit tests
    silent: true
    cmd: cd operator && cargo test
  helm-lint:
    desc: Run the helm linter
    silent: true
    cmd: ct lint --all --validate-maintainers=false
