apiVersion: v2
name: rustfs-manager-operator
description: A Helm chart for the RustFS Manager Operator
type: application
version: 0.1.2
appVersion: "0.1.2"
dependencies:
  - name: rustfs-manager-operator-docs
    alias: docs
    condition: docs.enabled
    repository: file://../rustfs-manager-operator-docs
    version: "*"
maintainers:
  - name: Nikolai Rodionov
    email: allanger@badhouseplants.net
    url: https://allanger.xyz
