{{- if .Values.rbac.create -}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "rustfs-manager-operator.name" . }}
  labels:
    {{- include "rustfs-manager-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch

- apiGroups:
  - rustfs.badhouseplants.net
  resources:
  - rustfsbuckets
  - rustfsinstances
  - rustfsbucketusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - rustfs.badhouseplants.net
  resources:
  - rustfsbuckets/finalizers
  - rustfsintsances/finalizers
  - rustfsbucketusers/finalizers
  verbs:
  - update

- apiGroups:
  - rustfs.badhouseplants.net
  resources:
  - rustfsbuckets/status
  - rustfsinstances/status
  - rustfsbucketusers/status
  verbs:
  - get
  - patch
  - update

- apiGroups:
  - "events.k8s.io"
  resources:
  - events
  verbs:
  - create
  - update
  - patch
  - get
  - list
  - watch
{{- end }}
