---
when:
  event:
    - pull_request
  branch:
    include:
      - main

matrix:
  include:
    - PACKAGE_NAME: badhouseplants/rustfs-manager-operator-docs-dev
      DIR: ./documentation
    - PACKAGE_NAME: badhouseplants/rustfs-manager-operator-dev
      DIR: ./operator

steps:
  - name: Build and push a dev container
    image: gitea.badhouseplants.net/badhouseplants/container-builder
    environment:
      REGISTRY_TOKEN:
        from_secret: GITEA_REGISTRY_TOKEN
      REGISTRY_USER: devops-bot
    privileged: true
    commands:
      - cd $DIR && build-container
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 700Mi
            cpu: 1000m
          limits:
            cpu: 1000m
        securityContext:
          privileged: true
