---
when:
  event:
    - tag

steps:
  - name: Build and push helm charts
    image: quay.io/helmpack/chart-testing:v3.14.0
    environment:
      REGISTRY_TOKEN:
        from_secret: GITEA_REGISTRY_TOKEN
      REGISTRY_USER: devops-bot
    commands:
      - apk update && apk add yq
      - helm registry login gitea.badhouseplants.net --username=$REGISTRY_USER --password=$REGISTRY_TOKEN

      - |-
        for chart in $(find helm -maxdepth 1 -mindepth 1 -type d); do
          if [ "$CI_COMMIT_BRANCH" != "main" ]; then
            yq e -i ".version += env(SHA)" "$chart/Chart.yaml"
          fi
          helm dep build $chart
          helm package $chart -d chart-packages;
        done
      - export CHARTS=$(find chart-packages -maxdepth 1 -mindepth 1 -type f)
      - export REGISTRY=$(echo oci://gitea.badhouseplants.net/$CI_REPO | tr '[:upper:]' '[:lower:]')
      - |-
        for chart in $CHARTS; do
          echo ${chart}
          CHART_NAME=$(helm show chart "${chart}" | yq .name)
          CHART_VERSION=$(helm show chart "${chart}" | yq .version)
          if helm pull ${REGISTRY}/${CHART_NAME}:${CHART_VERSION}; then
            echo "Chart is found in the upstream: ${CHART_NAME}:${CHART_VERSION}"
            continue;
          fi
          helm push "$chart" "$REGISTRY"
        done
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 700Mi
            cpu: 1000m
          limits:
            cpu: 1000m
        securityContext:
          privileged: true
