apiVersion: v2
name: rustfs-instance
description: Connect the rustfs manager operator to your RustFS instance
type: application
version: 0.1.3
appVersion: "0.1.3"
maintainers:
  - name: Nikolai Rodionov
    email: allanger@badhouseplants.net
    url: https://allanger.xyz
